source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
#use_frameworks!

target 'kk_espw' do
   	pod 'AFNetworking', '3.2.1'
    pod 'MJRefresh', '3.2.0'
    pod 'MJExtension', '3.1.0'
    pod 'bench_ios', :svn => 'https://huored.gicp.net:8088/svn/bench_ios/trunk/bench_ios_net/tags/v1.3.94’
    pod 'LoginLib', :svn =>'https://huored.gicp.net:8088/svn/kkcommon_sdk_ios/trunk/kk_sdk/kk_sdk/SDKs/LoginLib/tags/v1.0.0'
    pod 'LoginKit', :svn =>'https://huored.gicp.net:8088/svn/kkcommon_sdk_ios/trunk/kk_sdk/kk_sdk/SDKs/LoginKit/tags/v1.0.0'
    pod 'UITemplateKit', :svn => 'https://huored.gicp.net:8088/svn/bench_ios/trunk/UITemplate/tags/v1.0.2'
#   pod 'IMUIKit', :path => "/Users/jingtian9/IMUIKit_10_31_1_0_0/tags/v1.0.0"
    pod 'IMUIKit', :svn => 'https://huored.gicp.net:8088/svn/kkcommon_sdk_ios/trunk/kk_sdk/kk_sdk/SDKs/IMUIKit/tags/v1.0.0’

#    pod 'AMapLocation'
#    pod 'AMapSearch'
    pod 'Masonry', '1.1.0'
    pod 'FMDB', '2.7.5'

    pod 'AMapLocation', '2.6.2'
    pod 'AMapSearch', '6.9.0'
    pod 'Masonry', '1.1.0'
    pod 'FMDB', '2.7.5'
    #pod 'RongCloudIM/IMKit', '2.9.14'
    pod 'Bugly', '2.5.0'
    pod 'ZBarSDK', '~> 1.3.1'
    #原来用的3.1.1
    pod 'RongRTCLib', '3.1.3'
    pod 'JShare', '1.6.0'
    pod 'WechatOpenSDK_NoPay', '~> 1.8.0'
end
